### ISSUE TITLE
Rollup plugin strip() isn't working with Vite ? ( doesn't strip console.log() )

### ISSUE THREAD

**Issue by fabd** [patak-js/vite-rollup-plugins#1]
Hi

Great site! :+1: 

I tried to use the [Rollup strip plugin](https://github.com/rollup/plugins/tree/master/packages/strip), which is listed as "compatible".

I copied the config shown when clicking the little info icon:
          
```js
// ...
import strip from "@rollup/plugin-strip"

export default defineConfig({
  // other options here...
  
  plugins: [
    vue(),
    WindiCSS(),
    {
      ...strip(),
      apply: 'build',
    },
  ]
}
```

Somehow couldn't get it to work. Specifically: `console.log()` and `console.assert()` still showed after `vite build`.

Curiously no warnings or any errors from `vite build`, so the config appears to be syntactically correct at least.

I trried via rollupOptions as well but no luck:

```js
  build: {
    rollupOptions: {
       plugins: [strip()],
    },
```

Instead I remembered **an option in Terser**, and I was able to strip console statements this way :

```js
export default defineConfig({
  build: {
    terserOptions: {
      compress: {
        drop_console: true,
      },
    },
  },
```

Just wondering if the config for strip() is incorrect or there is something else it needs somehow?

**Comment by patak-cat** [comment]
Hey @fabd ! Thanks for the feedback and this report, great to see that you are using the listing 👍🏼 

About `@rollup/plugin-strip`, the [default value for the `include` config](https://github.com/rollup/plugins/tree/master/packages/strip#include) doesn't match against `.vue` files. You will need to do something like:

```js
  {
    ...strip({ include: '**/*.+(vue|js)' }),
    apply: 'build'
  }
```

We could add a note about this, but this is more general and it should be something framework agnostic.

**Comment by fabd** [comment]
Ah my bad. Thank you!

**Comment by fabd** [comment]
I can confirm this works:

```
    {
      ...strip({ include: "**/*.(js|ts)" }),
      apply: "build",
    },
```
I should have mentioned Typescript. It appears the plugin doesn't see the .vue file but sees the separate template/vue/script.

So logically speaking, for someone using plain javascript Vue (no TS), then the default options of the plugin should work.

Thanks again! I may edit the title for search engines because I often find some issues helpful myself when I google up things.

**Comment by patak-cat** [comment]
Thank you! And please get back if you find other things 🙌🏼 
I need to find a way to get people to send PRs with the community rollup plugins that they are using in their apps :)
