### ISSUE TITLE
rollup-plugin-rust

### ISSUE THREAD

**Issue by morenol** [patak-js/vite-rollup-plugins#11]
I would like  to make https://github.com/wasm-tool/rollup-plugin-rust compatible with vite, any hints of what I should do in order to accomplish that? 

Thanks in advance

**Comment by patak-cat** [comment]
Have you read this section of the docs: https://vitejs.dev/guide/api-plugin.html#rollup-plugin-compatibility ?
Maybe you could join https://chat.vitejs.dev if you have specific questions, there is a #plugins channel there and an active community and it could help you to log your progress as you investigate so others can chip in.
