### ISSUE TITLE
Vite 3

### ISSUE THREAD

**Issue by ghostdevv** [patak-js/vite-rollup-plugins#12]
Is it planned to make this list/a new list for Vite 3 plugins - personally I am specifically after a list of what plugins are already included in Vite 3

**Comment by patak-cat** [comment]
I'll work on getting it using the latest. About what official plugins are already included in Vite 3, there are the same that you see on the current page. That didn't change, the update will leave the site exactly the same if no regressions are discovered.

**Comment by ghostdevv** [comment]
Awesome thank you! Can close this now unless you want to keep it open for tracking :pray:

**Comment by patak-cat** [comment]
Lets keep it, thanks!

**Comment by patak-cat** [comment]
Done, thanks for the heads up!
https://twitter.com/patak_dev/status/1559821993553416192
