### ISSUE TITLE
Question: what is the difference between "covered" and "included" ?

### ISSUE THREAD

**Issue by HugoImaios** [patak-js/vite-rollup-plugins#19]
I think the descriptions of the Statuses are a bit ambiguous.
I get that "Covered" mean it's in the core functionality of Vite. But "shipped out of the box with Vite" means the same to me.
Does it means "Included" are maintained by Vite team, available in @vite npm namespace ?
Have a nice day

**Comment by patak-cat** [comment]
Included means that the rollup plugin is used by Vite directly (like plugin alias). Covered means that equivalent functionality is available (through a plugin implemented by Vite, like json support)

**Comment by HugoImaios** [comment]
oh OK. Makes sense that from a lambda developer like me who only use Vite, the two statuses are equivalent : nothing to add anywhere, just read the Vite doc
