### ISSUE TITLE
Plugin ordering issue in the eslint example (for Typescript files)

### ISSUE THREAD

**Issue by fabd** [patak-js/vite-rollup-plugins#2]
The eslint example didn't work out of the box because any typescript related eslint configs are applied _after_ source transform.

Esbuild transpiles `.ts` files to plain javascript, then eslint runs on its output. If eslint config has rules for typescript it complains about missing return types and whatnot. The giveaway is the line numbers are incorrect, and the errors in the IDE don't match those thrown on `vite build`.

Found the fix here: https://github.com/ehutch79/vite-eslint#warning

Adding the [`enforce` setting](https://vitejs.dev/guide/api-plugin.html#plugin-ordering) fixes the issue. The eslint worked as expected in serve and build modes:

```
{
      ...eslint({
        include: "./src/**/*.(vue|js|jsx|ts|tsx)",
      }),
      enforce: "pre",

      // uncomment this to lint only on `vite build`
      // apply: "build",
    },
```

As a side note,

in your examples you use file patterns like this: `'**/*.+(vue|js|jsx|ts|tsx)'`. I think this allows to match file..ts ? Is there a specific reason to allow "one or more dots" before the file extension?

**Comment by patak-cat** [comment]
Nice! I tested it without ts, good catch! Would you like to send a PR to add the enforce flag? 

About the +, it is a https://github.com/isaacs/minimatch pattern. They are not using regex for this.

**Comment by fabd** [comment]
> Would you like to send a PR to add the enforce flag?

Sure I guess I can learn a few things. Created a PR

PS: interestingly `vite` didn't work for me on a today's fork. Bunch of `No matching export for import "default"`

`vite build` worked.

**Comment by patak-cat** [comment]
There is a cache issue with the dev-server. I haven't been able to create a minimal reproduction for it, so I am unable to report the issue. When this happens, I remove the imports from `App.vue`, the dev fails in the browser, and the caches are busted. When I add back the imports, it works again. It happens when I update dependencies. It will surely be fixed soon :)

Thanks again for opening the first issue and creating the first PR for the project 🙌🏼

**Comment by patak-cat** [comment]
https://twitter.com/patak_js/status/1367487899621593097, thanks ;)

**Comment by fabd** [comment]
YW. Read your pinned article. Nice intro to Vite. I didn't even think much about it yet, but you are right, it truly is magic to have the almost instant feedback loop . It's like coming back to a time where Javascript & CSS was actually fun. I had to endure two years of nuxt ssr + tailwind, 3+ seconds of refresh time after a simple change in a vue file, routine crashes of nodejs, our laptops upgraded to 16 GB just to run a Javascript compiler, ugh..

And now you have WindiCSS that also almost instantly compiles the tailwind classes :)

**Comment by patak-cat** [comment]
Yes, we are entering a new stage in dev tooling. Looking forward to our IDEs also catching up
With tools and extensions like these ones https://twitter.com/vite_js/status/1366312716185526273
